name: Build and Deploy to S3

on:
  push:
    tags:
      - 'deploy-*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to S3
      uses: reggionick/s3-deploy@v4
      with:
        folder: dist
        bucket: ${{ secrets.AWS_S3_BUCKET }}
        bucket-region: 'us-west-2'
        invalidation: /
        delete-removed: true
        no-cache: true
        private: true
        files-to-include: '.*/*,*/*,**'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'
